create database coindispenserdb;

create table COIN(
   ID INT NOT NULL AUTO_INCREMENT,
   COIN_TYPE DECIMAL (2,2) NOT NULL UNIQUE,
   QTY_REMAINING INT NOT NULL,
   QTY_CONFIGURED INT NOT NULL,
   PRIMARY KEY ( ID )
);

INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.01,50,50);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.02,40,40);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.50,100,100);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.25,60,60);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.20,30,30);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.02,70,70);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.10,100,100);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.45,80,80);
	
COMMIT;