create database coindispenserdb;

create table COIN(
   ID INT NOT NULL AUTO_INCREMENT,
   COIN_TYPE DECIMAL (2,2) NOT NULL UNIQUE,
   QTY_REMAINING INT NOT NULL,
   QTY_CONFIGURED INT NOT NULL,
   PRIMARY KEY ( ID )
);

INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.01,100,100);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.05,100,100);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.10,100,100);
INSERT INTO COIN (COIN_TYPE,QTY_REMAINING,QTY_CONFIGURED) VALUES (0.25,100,100);
	
COMMIT;
